
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helm-deploy
  template:
    metadata:
      name: kubeserve
      labels:
        app: helm-deploy
    spec:
      containers:
      - image: sonal04/myaddressbookimage:7
        name: app
